/**
 * @license Copyright (c) 2003-2025, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-licensing-options
 */
import {
    ClassicEditor,
    Alignment,
    Autoformat,
    AutoImage,
    Base64UploadAdapter,
    BlockQuote,
    Bold,
    DataFilter,
    DataSchema,
    Essentials,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    GeneralHtmlSupport,
    Heading,
    Highlight,
    HorizontalLine,
    HtmlEmbed,
    Image,
    ImageCaption,
    ImageInsert,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Indent,
    IndentBlock,
    Italic,
    Link,
    LinkImage,
    List,
    ListProperties,
    MediaEmbed,
    MediaEmbedToolbar,
    Paragraph,
    PasteFromOffice,
    RemoveFormat,
    SourceEditing,
    Strikethrough,
    Style,
    Subscript,
    Superscript,
    Table,
    TableCaption,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    TextTransformation,
    TodoList,
    Underline,
    BlockToolbar,
    HeadingButtonsUI,
    ParagraphButtonUI,
} from 'ckeditor5';

//import FontColor from '@packages/font-color/src/fontcolor.js';

//import CKEditorInspector from '@ckeditor/ckeditor5-inspector';

import translations from 'ckeditor5/translations/ja.js';

import 'ckeditor5/ckeditor5.css';

/**
 * Create a free account with a trial: https://portal.ckeditor.com/checkout?plan=free
 */
const LICENSE_KEY = 'GPL'; // or <YOUR_LICENSE_KEY>.

class Editor extends ClassicEditor {}

// Plugins to include in the build.
Editor.builtinPlugins = [
    Alignment,
    Autoformat,
    AutoImage,
    Base64UploadAdapter,
    BlockQuote,
    Bold,
    DataFilter,
    DataSchema,
    Essentials,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    GeneralHtmlSupport,
    Heading,
    Highlight,
    HorizontalLine,
    HtmlEmbed,
    Image,
    ImageCaption,
    ImageInsert,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Indent,
    IndentBlock,
    Italic,
    Link,
    LinkImage,
    List,
    ListProperties,
    MediaEmbed,
    MediaEmbedToolbar,
    Paragraph,
    PasteFromOffice,
    RemoveFormat,
    SourceEditing,
    Strikethrough,
    Style,
    Subscript,
    Superscript,
    Table,
    TableCaption,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    TextTransformation,
    TodoList,
    Underline,
    BlockToolbar,
    ParagraphButtonUI,
    HeadingButtonsUI,
];

// Editor configuration.
Editor.defaultConfig = {
    language: 'ja',
    licenseKey: LICENSE_KEY,
    translations: [translations],
    toolbar: {
        items: [
            'heading',
            '|',
            'fontSize',
            'fontFamily',
            'fontColor',
            'fontBackgroundColor',
            'highlight',
            '|',
            'bold',
            'italic',
            'underline',
            'strikethrough',
            'subscript',
            'superscript',
            'removeFormat',
            '|',
            'alignment',
            'outdent',
            'indent',
            '|',
            'bulletedList',
            'numberedList',
            'todoList',
            '-',
            'style',
            '|',
            'undo',
            'redo',
            '|',
            'link',
            'imageInsert',
            'insertTable',
            'mediaEmbed',
            '|',
            'blockQuote',
            'horizontalLine',
            {
                label: 'Others',
                tooltip: 'Additional editing features',
                items: ['htmlEmbed', 'sourceEditing'],
            },
        ],
        shouldNotGroupWhenFull: true,
    },
    blockToolbar: {
        items: [
            'paragraph',
            '|',
            'heading1',
            'heading2',
            'heading3',
            'heading4',
            'heading5',
            'heading6',
            '|',
            'blockQuote',
        ],
        shouldNotGroupWhenFull: true,
    },
    fontFamily: {
        options: [
            'default',
            '源ノ角ゴシック, Noto Sans JP, sans-serif',
            '源ノ角明朝, SourceHanSerif, serif',
            'さつき現代明朝, SatsukiGendaiMincho, serif',
        ],
    },
    fontSize: {
        options: [
            {
                title: '極小',
                model: '0.7em',
            },
            {
                title: '小',
                model: '0.85em',
            },
            'default',
            {
                title: '大',
                model: '1.4em',
            },
            {
                title: '極大 1.8',
                model: '1.8em',
            },
            {
                title: '極大 2.4',
                model: '2.4em',
            },
        ],
        supportAllValues: true,
    },
    heading: {
        options: [
            { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
            { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
            { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
            { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
            { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
            { model: 'heading5', view: 'h5', title: 'Heading 5', class: 'ck-heading_heading5' },
            { model: 'heading6', view: 'h6', title: 'Heading 6', class: 'ck-heading_heading6' },
        ],
    },
    image: {
        toolbar: [
            'imageStyle:inline',
            // 'imageStyle:block',
            // 'imageStyle:side',
            'imageStyle:alignLeft',
            'imageStyle:alignCenter',
            'imageStyle:alignRight',
            '|',
            'toggleImageCaption',
            'imageTextAlternative',
            '|',
            'linkImage',
        ],
        // resizeUnit: 'px',
    },
    table: {
        contentToolbar: ['tableColumn', 'tableRow', 'mergeTableCells', 'tableCellProperties', 'tableProperties'],
    },
    mediaEmbed: {
        removeProviders: ['instagram', 'twitter', 'googleMaps', 'flickr', 'facebook'],
        previewsInData: true,
    },
    htmlSupport: {
        allow: [
            {
                name: /^(div|section|article|aside)$/,
                attributes: {
                    id: true,
                    name: true,
                },
                classes: true,
                styles: true,
            },
            {
                name: /^(p|h[1-6])$/,
                classes: true,
                styles: true,
            },
            {
                name: 'a',
                attributes: {
                    target: true,
                    name: true,
                },
                classes: true,
                styles: true,
            },
            {
                name: 'img',
                attributes: {
                    src: true,
                    alt: true,
                    width: true,
                    height: true,
                    sizes: true,
                    srcset: true,
                    crossorigin: true,
                    decoding: true,
                    loading: true,
                    referrerpolicy: true,
                },
                classes: true,
                styles: true,
            },
            {
                name: 'iframe',
                attributes: true,
                classes: true,
                styles: true,
            },
            {
                name: /^(span|br|figure|figcaption|hr|ul|li)$/,
                classes: true,
                styles: true,
            },
            {
                name: /^(b|i|u|pre|s|small|strong|sub|sup|details|summary)$/,
            },
            {
                name: /^(q|blockquote)$/,
                attributes: {
                    cite: true,
                },
            },
        ],
    },
};

export default Editor;
